// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzzgmrxxmifwlrepgukl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6emdtcnh4bWlmd2xyZXBndWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODQyNjUsImV4cCI6MjA1ODA2MDI2NX0.c9qxiVZuRAFS9tiloNuxHXUSzy7Id4o08Q3ScYzQy6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);